openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Products API"
  description: "API for managing products in your application"

securityDefinitions:
  BearerToken:
    type: apiKey
    name: Authorization
    in: header

paths:
  /products/insertion:
    get:
      summary: Insert products
      description: Insert products from a data source.
      tags:
        - Products
      security:
        - BearerToken: []
      responses:
        200:
          description: Products inserted successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Product"
        500:
          description: Internal server error

  /products/mockproducts:
    get:
      summary: Generate mocking products
      description: Generate mocking products for testing.
      tags:
        - Products
      security:
        - BearerToken: []
      responses:
        200:
          description: Mocking products generated successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Product"
        500:
          description: Internal server error

  /products:
    get:
      summary: Get all products
      description: Retrieve a list of all products in the system.
      tags:
        - Products
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Product"
        500:
          description: Internal server error

    post:
      summary: Create a new product
      description: Create a new product in the system.
      tags:
        - Products
      security:
        - BearerToken: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/ProductInput"
            example:
              title: "Washburn X Series Electric Guitar"
              description: "A versatile electric guitar with great playability and tone"
              code: "WX200"
              price: 1200
              status: true
              stock: 10
              category: "Electric Guitar"
      responses:
        201:
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: "#/definitions/Product"
        400:
          description: Bad request
        500:
          description: Internal server error

  /products/{pid}:
    get:
      summary: Get a product by ID
      description: Retrieve product information by its ID.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: ID of the product to retrieve
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/definitions/Product"
        404:
          description: Product not found
        500:
          description: Internal server error

    put:
      summary: Update a product by ID
      description: Update product information by its ID.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: ID of the product to update
          required: true
          schema:
            type: string
        - name: product
          in: body
          description: Product object with updated information
          required: true
          content:
            application/json:
              schema:
                $ref: "#/definitions/ProductInput"
      responses:
        200:
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: "#/definitions/Product"
        400:
          description: Bad request
        404:
          description: Product not found
        500:
          description: Internal server error

    delete:
      summary: Delete a product by ID
      description: Delete a product by its ID.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: ID of the product to delete
          required: true
          schema:
            type: string
      responses:
        200:
          description: Product deleted successfully
        404:
          description: Product not found
        500:
          description: Internal server error

definitions:
  ProductInput:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      code:
        type: string
      price:
        type: number
      status:
        type: boolean
      stock:
        type: number
      category:
        type: string

  Product:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      code:
        type: string
      price:
        type: number
      status:
        type: boolean
      stock:
        type: number
      category:
        type: string