openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Carts API"
  description: "API for managing shopping carts in your application"

securityDefinitions:
  BearerToken:
    type: apiKey
    name: Authorization
    in: header

paths:
  /carts/insertion:
    get:
      summary: Insert shopping carts
      description: Insert shopping carts from a data source.
      tags:
        - Carts
      responses:
        200:
          description: Shopping carts inserted successfully
        500:
          description: Internal server error

  /carts:
    get:
      summary: Get all shopping carts
      description: Retrieve a list of all shopping carts in the system.
      tags:
        - Carts
      responses:
        200:
          description: Successful operation
        500:
          description: Internal server error

    post:
      summary: Create a new shopping cart
      description: Create a new shopping cart in the system.
      tags:
        - Carts
      parameters:
        - name: cart
          in: body
          description: Shopping cart object to be created
          required: true
          schema:
            $ref: "#/definitions/CartInput"
          example:
            products:
              - product: "65323942de6f521bf2d57001"
                quantity: 3
              - product: "65323942de6f521bf2d5700f"
                quantity: 1
      responses:
        201:
          description: Shopping cart created successfully
          schema:
            $ref: "#/definitions/Cart"
        400:
          description: Bad request
        500:
          description: Internal server error

  /carts/{cid}:
    get:
      summary: Get a shopping cart by ID
      description: Retrieve shopping cart information by its ID.
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          description: ID of the shopping cart to retrieve
          required: true
          type: string
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/Cart"
        404:
          description: Shopping cart not found
        500:
          description: Internal server error

    put:
      summary: Update a shopping cart by ID
      description: Update shopping cart information by its ID.
      tags:
        - Carts
      security:
      - BearerToken: []
      parameters:
        - name: cid
          in: path
          description: ID of the shopping cart to update
          required: true
          type: string
        - name: cart
          in: body
          description: Shopping cart object with updated information
          required: true
          schema:
            $ref: "#/definitions/CartInput"
      responses:
        200:
          description: Shopping cart updated successfully
          schema:
            $ref: "#/definitions/Cart"
        400:
          description: Bad request
        404:
          description: Shopping cart not found
        500:
          description: Internal server error

    delete:
      summary: Delete a shopping cart by ID
      description: Delete a shopping cart by its ID.
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          description: ID of the shopping cart to delete
          required: true
          type: string
      responses:
        200:
          description: Shopping cart deleted successfully
        404:
          description: Shopping cart not found
        500:
          description: Internal server error

  /carts/purchase:
    post:
      summary: Purchase a shopping cart
      description: Purchase a shopping cart by its ID.
      tags:
        - Carts
      parameters:
        - name: cartId
          in: body
          description: ID of the shopping cart to purchase
          required: true
          schema:
            type: string
        - name: email
          in: body
          description: Email of the purchaser
          required: true
          schema:
            type: string
      responses:
        200:
          description: Shopping cart purchased successfully
        400:
          description: Bad request
        404:
          description: Shopping cart not found
        500:
          description: Internal server error

definitions:
  CartInput:
    type: object
    properties:
      products:
        type: array
        items:
          $ref: "#/definitions/CartProductInput"

  CartProductInput:
    type: object
    properties:
      product:
        type: string
      quantity:
        type: integer

  Cart:
    type: object
    properties:
      products:
        type: array
        items:
          $ref: "#/definitions/CartProduct"
